ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "franchiseeId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Engineer" ADD COLUMN IF NOT EXISTS "franchiseeId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "franchiseeId" TEXT NOT NULL DEFAULT '';
